from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .vanilla-ziyu import *
from .scholar-ziyu import *
from .dummy import *
from .dummy1 import *
from .dummy2 import *
from .dummy3 import *
from .scrappy_the_cholo import *
from .mathgeni import *
from .mathgeni1 import *
from .mathgeni import *
